name: Build, Test, and Lint Docker Image

on:
  push:
#    paths:
#      - 'Dockerfile' # Trigger the workflow only if Dockerfile is modified
    branches:
      - master # Trigger the workflow only if the push is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ajinkya924/assignment1:latest .

  test:
    needs: build # Only run the test job if the build job is successful
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test Docker image
      run: |
        docker run -d -p 80:80 --name test1 ajinkya924/assignment1:latest
        sleep 10  # Wait for the application to start
        curl localhost:80 || exit 1

  lint:
    needs: [ build, test ] # Only run the build and test job if the build job is successful
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Dockerfilelint
      run: |
        docker run -v `pwd`/Dockerfile:/Dockerfile replicated/dockerfilelint /Dockerfile

    - name: Run dive
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive --ci ajinkya924/assignment1:latest  
              
  push:
    needs: [build, test, lint] # Only run the push job if the build, test, and lint jobs are successful
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Set the username as a secret in your repository
        password: ${{ secrets.DOCKER_PASSWORD }} # Set the password as a secret in your repository

    - name: Push Docker image
      run: docker push ajinkya924/assignment1:latest
